### ISSUE TITLE
Logger complains about java 7

### ISSUE THREAD

**Issue by scpeters** [ihmcrobotics/ihmc-logger-docker#1]
I just tried running the docker container pulled from docker hub, and it was failing silently. So I started an interactive version of the container and invoked the logger command manually, and I got the following error message:

~~~
# /root/IHMCLogger/bin/IHMCLogger -n -d /root/robotLogs/
Exception in thread "main" java.lang.UnsupportedClassVersionError: us/ihmc/robotDataLogger/logger/YoVariableLoggerDispatcher : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
~~~

It has openjdk 7.

~~~
# java -version
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
~~~

Maybe the tarball downloaded [here](https://github.com/ihmcrobotics/ihmc-logger-docker/blob/master/no_cameras/Dockerfile#L29) actually needs java 8?

**Comment by dljsjr** [comment]
@scpeters `latest` or `0.9.1-no_cameras` should address this. Sorry about that!
